"""Add link table

Revision ID: ea3ec0051540
Revises: 32da89362c76
Create Date: 2025-03-03 18:12:17.664738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3ec0051540'
down_revision: Union[str, None] = '32da89362c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('live_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='link_shortener'
    )
    op.create_index(op.f('ix_link_shortener_link_id'), 'link', ['id'], unique=False, schema='link_shortener')
    op.create_index(op.f('ix_link_shortener_link_short_url'), 'link', ['short_url'], unique=True, schema='link_shortener')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_shortener_link_short_url'), table_name='link', schema='link_shortener')
    op.drop_index(op.f('ix_link_shortener_link_id'), table_name='link', schema='link_shortener')
    op.drop_table('link', schema='link_shortener')
    # ### end Alembic commands ###
